name: OpenWebUI
services:
  OpenWebUI:
    image: ghcr.io/open-webui/open-webui:v0.11.3@sha256:751b617714b91e4cfd0186a509c72480c858e012976103b09a30dad053c36175
    container_name: OpenWebUI
    restart: unless-stopped
    hostname: openwebui
    networks:
      - OpenWebUI
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - CORS_ALLOW_ORIGIN=https://${OPENWEBUI_HOST}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENABLE_IMAGE_GENERATION=false
      - ENABLE_OLLAMA_API=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES}/OpenWebUI:/app/backend/data

    user: "${UID}:${GID}"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald

    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
          pids: 256

networks:
  OpenWebUI:
    name: OpenWebUI
    external: true
